version: '3'
services:
    rabbitmq:
        image: rabbitmq:3.7.7-management-alpine
        container_name: rabbitmq
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: rabbithlt
            RABBITMQ_DEFAULT_PASS: sonic333
            RABBITMQ_DEFAULT_VHOST: yiye_beta
        ports:
        - 15673:15672
        - 5673:5672
        networks:
        - rabbitmq
        volumes:
        - ~/volumes/rabbitmq/data/:/var/lib/rabbitmq/
networks:
    rabbitmq:
