version: '3'
services:
    postgresql:
        image: postgres:10.5-alpine
        container_name: postgresql
        volumes:
        - ~/volumes/postgresql/:/var/lib/postgresql/data/
        environment:
        - POSTGRES_USER=postgresuser
        - POSTGRES_PASSWORD=sonic333
        - TZ=Asia/Shanghai
        ports:
        - 5432:5432
        networks:
        - postgresql

networks:
    postgresql:
