version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    depends_on:
      - app
      - postgres
    networks:
        - default
        - info
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
  postgres:
    restart: always
    container_name: postgres
    image: postgres
    networks:
        - default
        - info
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: info_data
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: sonic333
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./PG_DATA:/var/lib/postgresql/data/pgdata

  app:
    restart: always
    container_name: yiduo-blog
    image: 192.168.0.7/hlt/information:test
    networks:
      - default
      - info
    volumes:
      - ./logs:/tmp/data/info/logl
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/info_data
    ports:
      - "8200:8080"
    depends_on:
      - postgres
networks:
    info:
        external: true
